

spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 486206640184103
            client-secret: 4612be1a329c5652fac37a48b1849369
          google:
            client-id: 30944815160-5e53ash14ooj8fq4o311cjsrh8p2npic.apps.googleusercontent.com
            client-secret: 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
          github:
            clientId: 8b8dbab05e50f55b474c
            clientSecret: f1a4e8a14422160c22ed7cdefda4e5f4e4ef95a9